DROP = 'drop'
CLASS = 'class'

datasets = {'infant_mortality.csv': {CLASS: 'region'},
            'biomass.csv': {CLASS: 'species'},
            'highway.csv': {CLASS: 'htype'},
            'soils.csv': {CLASS: 'Contour'},
            'iris.csv': {CLASS: 'Species'},
            'Caterpillars.csv': {CLASS: 'ActiveFeeding'},
            'skulls.csv': {CLASS: 'epoch'},
            'hla.csv': {CLASS: 'id'},
            'Tobacco.csv': {CLASS: 'occupation'},
            'Mroz.csv': {CLASS: 'city'},
            'Kakadu.csv': {CLASS: 'answer'},
            'Fishing.csv': {CLASS: 'mode'},
            'Fatality.csv': {CLASS: 'jaild'},
            'Benefits.csv': {CLASS: 'joblost', DROP: ['bluecol']},
            'DoctorAUS.csv': {CLASS: 'insurance'},
            'MedGPA.csv': {CLASS: 'Accept', DROP: ['Acceptance']},
            'InstInnovation.csv': {CLASS: 'sp500', DROP: ['company']},
            'InsuranceVote.csv': {CLASS: 'Party', DROP: ['Dist.', 'Rep', 'Dem']},
            'Hoops.csv': {CLASS: 'Opp', DROP: ['Game']},
            'midwest.csv': {CLASS: 'category', DROP: ['PID', 'county', 'state']},
            'msleep.csv': {CLASS: 'vore', DROP: ['name', 'genus', 'order']},
            'Crime.csv': {CLASS: 'region', DROP: ['county']},
            'Caschool.csv': {CLASS: 'county', DROP: ['distcod', 'district']},
            }

datasets_small = {'infant_mortality.csv': {CLASS: 'region'},
                  'biomass.csv': {CLASS: 'species'},
                  'highway.csv': {CLASS: 'htype'},
                  'iris.csv': {CLASS: 'Species'},
                  'Tobacco.csv': {CLASS: 'occupation'},
                  'Fishing.csv': {CLASS: 'mode'},
                  'Fatality.csv': {CLASS: 'jaild'},
                  'MedGPA.csv': {CLASS: 'Accept', DROP: ['Acceptance']},
                  'InsuranceVote.csv': {CLASS: 'Party', DROP: ['Dist.', 'Rep', 'Dem']},
                  'Hoops.csv': {CLASS: 'Opp', DROP: ['Game']},
                  'midwest.csv': {CLASS: 'category', DROP: ['PID', 'county', 'state']},
                  'msleep.csv': {CLASS: 'vore', DROP: ['name', 'genus', 'order']},
                  'Caschool.csv': {CLASS: 'county', DROP: ['distcod', 'district']},
                  }

datasets_reg = {
    'honeyproduction.csv': {CLASS: 'stocks', DROP: ['year']},
    'aids.csv': {CLASS: 'y'},
    'diamonds.csv': {CLASS: 'price', DROP: ['cut', 'color', 'clarity']},
    'cars04.csv': {CLASS: 'SuggestedRetailPrice', DROP: ['Hybrid', 'DealerCost']},
    'pgatour2006.csv': {CLASS: 'PrizeMoney', DROP: ['TigerWoods']},
    'magazines.csv': {CLASS: 'AdRevenue'},
    'insurance.csv': {CLASS: 'charges'},
    'Bordeaux.csv': {CLASS: 'Price', DROP: ['P95andAbove', 'FirstGrowth', 'CultWine', 'Pomerol', 'VintageSuperstar']},
    'house_data.csv': {CLASS: 'price', DROP: ['date']},
    'longley.csv': {CLASS: 'GNP.deflator', DROP: ['Year']},
    'winequality-white.csv': {CLASS: 'alcohol', DROP: ['quality']},
    'weatherHistory.csv': {CLASS: 'Apparent Temperature (C)', DROP: ['Summary', 'Precip Type', 'Daily Summary',
                                                                     'Loud Cover', 'Visibility (km)']},
}

datasets_rbf = {
    'annealing.csv': {CLASS: 'classes'},
    'balance-scale.csv': {CLASS: 'Class-Name'},
    'breast-cancer.csv': {CLASS: 'Class'},
    'breast-cancer-wdbc.csv': {CLASS: 'Diagnosis', DROP: ['ID']},
    'breast-cancer-wisconsin.csv': {CLASS: 'Class', DROP: ['id']},
    'bridges-version1.csv': {CLASS: 'TYPE', DROP: ['ID']},
    'bridges-version2.csv': {CLASS: 'TYPE', DROP: ['ID']},
    'dermatology.csv': {CLASS: 'class'},
    'ecoli.csv': {CLASS: 'class', DROP: ['Seq']},
    'flags.csv': {CLASS: 'religion', DROP: ['name']},
    'glass.csv': {CLASS: 'type', DROP: ['Id']},
    'haberman.csv': {CLASS: 'survived'},
    'iris.csv': {CLASS: 'Species', DROP: ['idx']},
    'post-operative.csv': {CLASS: 'ADM-DECS'},
    'primary-tumor.csv': {CLASS: 'class'},
    'soybean-large.csv': {CLASS: 'class'},
    'tic-tac-toe.csv': {CLASS: 'Class'},
}
